[package]
name = "xz"
version = "5.2.5"
nanvix-version = "0.16.115"

[builds]
[builds.matrix]
platforms = ["hyperlight", "microvm"]
modes = ["multi-process", "single-process", "standalone"]
memory = ["128mb", "256mb"]
